language: shell

sudo: required

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version

script:
  - docker-compose build
  - docker-compose up -d
  - docker-compose images
  - docker-compose ps
  - sleep 1s
  - docker-compose down
